"""
confound_audit_gse146889.py -- confound-attribution audit for the GSE146889 cohort
(176 samples: 91 tumor, 85 normal, gene-count/RPKM matrix), reproducing
results/confound_attribution_audit/confound_audit_GSE146889.md.

**PROVENANCE CAVEAT (read before trusting this script's exact-match claims):** the
original run of this cohort's audit was performed by a delegated sub-agent whose
producing code is NOT reachable via this project's normal code-lineage mechanism (the
report artifact's lineage graph has only 1 node -- itself -- with no upstream chain).
This script was reconstructed by manually walking that sub-agent's full conversation
transcript (~95 python/bash tool-use cells) and re-assembling the pipeline in dependency
order. This is a fundamentally more error-prone extraction method than the lineage-based
reconstruction used for the other 3 cohorts (GSE81089, CPTAC-CCRCC, TCGA-LUAD), which
pulled exact producing code directly. Treat this script as a faithful best-effort
reconstruction, not a byte-exact replay -- verified below against the committed report's
numbers, but with headroom for small discrepancies in tie-breaks / exact null seeds that
the original transcript did not always print explicitly.

Data source: NCBI GEO series GSE146889, supplementary gene-count/RPKM matrix
(GSE146889_GeneCount.tsv.gz), columns ending in "_rpkm"; tumor/normal assigned by
whether "tumor"/"normal" appears in the sample column name (this cohort's naming
convention, distinct from GSE81089's "_T"/"_N" suffix convention).

Preprocessing: log1p(RPKM) -> drop zero-variance genes -> top-2000 HVG by variance ->
per-feature StandardScaler -> PCA(50). Backend: ripser.

**IMPORTANT: the mixed-set null distributions (Gaussian n=500 draws, permutation n=2000
draws, both in PCA(50) space) are NOT regenerated by this script -- they are REUSED from
the cohort's original Phase-1 cross-dataset-replication run** (same null the replication
report itself used), loaded from two artifacts this script fetches by id
(null_distributions_GSE146889.pkl, diagrams_GSE146889.pkl). Only the within-class,
within-stratum, and residualization CONTROLS were run fresh for the confound audit; the
mixed-set null was correctly treated as already-computed and not wastefully rerun. This
matches what the sub-agent transcript actually did (cell 109 in the reconstructed
transcript loads these two pickles by artifact id rather than regenerating them).

Expected results (from the committed report): mixed max-H1 = 7.564, tumor-only max-H1 =
5.880 (does NOT match mixed -- reported finding, not a bug), residualized z_gaussian ~=
14.35.
"""
import os
import sys
import time
import argparse
import pickle
import numpy as np
import pandas as pd
import urllib.request
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _ROOT)
from confound_audit_common import (
    max_h1_persistence, within_class_decomposition, confound_direction,
    within_stratum_control, residualization_control, block_bootstrap_ci, zscore_pvalue,
)

# Artifact ids of the ORIGINAL Phase-1 replication run's null distributions for this
# cohort (reused here, not regenerated -- see module docstring)
REUSED_NULL_DISTS_ARTIFACT = "4f17d41c-f21c-4620-812b-6f1a44a541e2"
REUSED_DIAGRAMS_ARTIFACT = "d091cf0c-798f-49a8-b9ad-fc7e0c97d40c"


def fetch_gse146889(data_dir):
    os.makedirs(data_dir, exist_ok=True)
    url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE146nnn/GSE146889/suppl/GSE146889_GeneCount.tsv.gz"
    out = os.path.join(data_dir, "GSE146889_GeneCount.tsv.gz")
    if not os.path.exists(out):
        urllib.request.urlretrieve(url, out)
    df = pd.read_csv(out, sep="\t")
    df2 = df.iloc[:-1].copy()  # drop footer row
    rpkm_cols = [c for c in df2.columns if c.endswith("_rpkm")]
    sample_names = [c[:-5] for c in rpkm_cols]  # strip "_rpkm"
    tumor_mask = np.array(["tumor" in s.lower() for s in sample_names])

    rpkm = df2[rpkm_cols].to_numpy(dtype=float)  # genes x samples
    return rpkm, sample_names, tumor_mask


def preprocess(rpkm, n_hvg=2000):
    log_rpkm = np.log1p(rpkm)
    X = log_rpkm.T  # samples x genes
    gene_var = X.var(axis=0, ddof=0)
    nonzero_var_mask = gene_var > 0
    X_nz = X[:, nonzero_var_mask]
    var_nz = gene_var[nonzero_var_mask]
    hvg_order = np.argsort(-var_nz)
    top_idx = hvg_order[:n_hvg]
    X_hvg = X_nz[:, top_idx]
    scaler = StandardScaler()
    X_hvg_std = scaler.fit_transform(X_hvg)
    return X_hvg_std, X_nz  # X_nz = all nonzero-var genes (log1p space, pre-HVG-selection),
                             # needed for pipeline-symmetric permutation nulls that reselect HVG


_BUNDLED_NULL_DIR = os.path.join(_ROOT, "data_gse146889_reused_null")


def load_reused_null(artifact_root=None):
    """Load the reused mixed-set null distributions from the original Phase-1 replication
    run for this cohort (see module docstring). These two pickles are bundled in this repo
    at data_gse146889_reused_null/ (52 KB total) for portability -- no artifact-store or
    network access needed. artifact_root overrides the bundled location if given."""
    search_dir = artifact_root or _BUNDLED_NULL_DIR
    null_path = os.path.join(search_dir, "null_distributions_GSE146889.pkl")
    diag_path = os.path.join(search_dir, "diagrams_GSE146889.pkl")
    if not (os.path.isfile(null_path) and os.path.isfile(diag_path)):
        raise RuntimeError(
            f"Reused null-distribution pickles not found in {search_dir}. "
            "They should be bundled at code/confound_attribution_audit/data_gse146889_reused_null/ "
            "in this repo; pass --local-null-dir to point elsewhere."
        )
    with open(null_path, "rb") as f:
        null_dists = pickle.load(f)
    with open(diag_path, "rb") as f:
        diagrams = pickle.load(f)
    return null_dists, diagrams


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=os.path.join(_ROOT, "data_gse146889"))
    ap.add_argument("--results-dir", default=os.path.join(_ROOT, "results_gse146889"))
    ap.add_argument("--local-null-dir", default=None,
                     help="Directory with the reused null pickles, if not running inside "
                          "a Claude Science kernel (see load_reused_null docstring)")
    ap.add_argument("--n-gauss", type=int, default=300)
    ap.add_argument("--n-perm", type=int, default=300)
    ap.add_argument("--n-boot", type=int, default=2000)
    ap.add_argument("--quick", type=int, default=None)
    args = ap.parse_args()
    if args.quick:
        args.n_gauss = min(args.n_gauss, args.quick)
        args.n_perm = min(args.n_perm, args.quick)
        args.n_boot = min(args.n_boot, args.quick)
        print(f"[QUICK MODE] capping all draw counts to {args.quick}")

    os.makedirs(args.results_dir, exist_ok=True)
    t0 = time.time()
    rpkm, sample_names, tumor_mask = fetch_gse146889(args.data_dir)
    X_hvg_std, X_nz_allgenes = preprocess(rpkm)
    print(f"Loaded GSE146889: {X_hvg_std.shape}, tumor={tumor_mask.sum()}, normal={(~tumor_mask).sum()} ({time.time()-t0:.0f}s)")

    BACKEND = "ripser"
    pca = PCA(n_components=50, random_state=42)
    X_pca50 = pca.fit_transform(X_hvg_std)
    obs_mixed_pca = max_h1_persistence(X_pca50, backend=BACKEND)

    null_dists, _diagrams = load_reused_null(args.local_null_dir)
    gauss_pca_mixed = np.asarray(null_dists["gaussian_pca"])
    perm_pca_mixed = np.asarray(null_dists["perm_pca"])
    print(f"Reused mixed-set null (from Phase-1 replication run): "
          f"gaussian n={len(gauss_pca_mixed)} mean={gauss_pca_mixed.mean():.3f}, "
          f"perm n={len(perm_pca_mixed)} mean={perm_pca_mixed.mean():.3f}")

    z_gauss_mixed = zscore_pvalue(obs_mixed_pca, gauss_pca_mixed)
    z_perm_mixed = zscore_pvalue(obs_mixed_pca, perm_pca_mixed)
    print(f"  mixed (PCA50) observed={obs_mixed_pca:.4f} z_gauss={z_gauss_mixed['z']:.2f} z_perm={z_perm_mixed['z']:.2f}")
    np.testing.assert_allclose(obs_mixed_pca, 7.564, atol=0.05)
    print("  VERIFIED: mixed max-H1 (PCA50) matches expected value 7.564 (atol 0.05)")

    # --- Control 1: within-class decomposition (raw HVG->PCA50 per-subset pipeline) ---
    print("\n=== Control 1: within-class decomposition ===")

    def full_pipeline_from_lograpkm(X_allgenes_subset, n_hvg=2000, n_pca=50, seed=42):
        var = X_allgenes_subset.var(axis=0, ddof=0)
        nz_mask = var > 0
        Xnz = X_allgenes_subset[:, nz_mask]
        var_nz = Xnz.var(axis=0, ddof=0)
        top_idx = np.argsort(-var_nz)[:n_hvg]
        Xhvg = Xnz[:, top_idx]
        Xstd = StandardScaler().fit_transform(Xhvg)
        n = Xstd.shape[0]
        p = PCA(n_components=min(n_pca, n - 1, n_hvg), random_state=seed)
        Xpca = p.fit_transform(Xstd)
        return Xpca

    # need the raw (pre-HVG) log-rpkm matrix per subset to reselect HVG within each subset
    X_log_all = np.log1p(rpkm).T  # samples x all genes (unfiltered)
    Xpca_tumor = full_pipeline_from_lograpkm(X_log_all[tumor_mask])
    Xpca_normal = full_pipeline_from_lograpkm(X_log_all[~tumor_mask])
    obs_tumor = max_h1_persistence(Xpca_tumor, backend=BACKEND)
    obs_normal = max_h1_persistence(Xpca_normal, backend=BACKEND)

    gauss_tumor = np.random.RandomState(10000)  # placeholder rng, replaced by null generation below
    from confound_audit_common import gaussian_null_maxh1, permutation_null_maxh1_pca_refit
    gauss_tumor_draws = gaussian_null_maxh1(tumor_mask.sum(), 2000, args.n_gauss, seed=10000, n_pca=50, backend=BACKEND)
    gauss_normal_draws = gaussian_null_maxh1((~tumor_mask).sum(), 2000, args.n_gauss, seed=20000, n_pca=50, backend=BACKEND)
    perm_tumor_draws = permutation_null_maxh1_pca_refit(X_nz_allgenes[tumor_mask], 50, args.n_perm, seed=40000, backend=BACKEND)
    perm_normal_draws = permutation_null_maxh1_pca_refit(X_nz_allgenes[~tumor_mask], 50, args.n_perm, seed=50000, backend=BACKEND)

    z_gauss_tumor = zscore_pvalue(obs_tumor, gauss_tumor_draws)
    z_perm_tumor = zscore_pvalue(obs_tumor, perm_tumor_draws)
    z_gauss_normal = zscore_pvalue(obs_normal, gauss_normal_draws)
    z_perm_normal = zscore_pvalue(obs_normal, perm_normal_draws)
    print(f"  mixed  n=176 obs={obs_mixed_pca:.3f} z_gauss={z_gauss_mixed['z']:.2f} z_perm={z_perm_mixed['z']:.2f}")
    print(f"  tumor  n={tumor_mask.sum():3d} obs={obs_tumor:.3f} z_gauss={z_gauss_tumor['z']:.2f} z_perm={z_perm_tumor['z']:.2f}")
    print(f"  normal n={(~tumor_mask).sum():3d} obs={obs_normal:.3f} z_gauss={z_gauss_normal['z']:.2f} z_perm={z_perm_normal['z']:.2f}")
    print(f"  Mixed vs tumor-only DO NOT match ({obs_mixed_pca:.3f} vs {obs_tumor:.3f}) -- "
          f"consistent with the reported finding.")
    np.testing.assert_allclose(obs_tumor, 5.880, atol=0.3)
    print("  VERIFIED (loose tolerance, reconstructed pipeline): tumor-only max-H1 close to expected 5.880")

    # --- Control 2: within-stratum quartile control (bin by confound-direction projection) ---
    print("\n=== Control 2: within-stratum quartile control ===")
    u, proj_full = confound_direction(X_hvg_std, tumor_mask)
    q_id = pd.qcut(proj_full, 4, labels=False)
    X_by_stratum_pca = []
    perm_source_by_stratum = []
    for i in range(4):
        idx = np.where(q_id == i)[0]
        X_by_stratum_pca.append(full_pipeline_from_lograpkm(X_log_all[idx]))
        perm_source_by_stratum.append(X_nz_allgenes[idx])
    strata_df = within_stratum_control(X_by_stratum_pca, n_gauss=min(args.n_gauss, 300), backend=BACKEND,
                                        seed_base=30000, perm_source_by_stratum=perm_source_by_stratum,
                                        n_perm=min(args.n_perm, 300))
    print(strata_df[["quartile", "n", "observed", "gauss_z", "gauss_p"]].to_string(index=False))

    # --- Control 3: residualization ---
    print("\n=== Control 3: residualization ===")
    resid = residualization_control(X_hvg_std, tumor_mask, n_pcs=50, n_gauss=args.n_gauss,
                                     n_perm=args.n_perm, backend=BACKEND, seed_base=9000)
    print(f"  max abs class-mean diff after residualization: {resid['max_abs_classmean_diff_after_resid']:.2e}")
    print(f"  intact:       observed={resid['intact']['observed']:.4f} AUC={resid['intact']['auc']:.4f} "
          f"z_gauss={resid['intact']['gauss']['z']:.2f}")
    print(f"  residualized: observed={resid['residualized']['observed']:.4f} AUC={resid['residualized']['auc']:.4f} "
          f"z_gauss={resid['residualized']['gauss']['z']:.2f}")
    if not args.quick:
        np.testing.assert_allclose(resid['residualized']['gauss']['z'], 14.35, rtol=0.3)
        print("  VERIFIED (loose tolerance, reconstructed pipeline): residualized z_gaussian close to expected ~14.35")
    else:
        print("  [QUICK MODE] skipping z_gaussian tolerance check (draw count reduced)")

    # --- Control 4: block-bootstrap CI (tumor-only) ---
    print("\n=== Control 4: block-bootstrap CI (tumor-only) ===")
    boot = block_bootstrap_ci(Xpca_tumor, z_gauss_tumor["null_mean"], z_gauss_tumor["null_sd"],
                               n_boot=args.n_boot, seed=200, backend=BACKEND)
    print(f"  delta 95% CI: [{boot['ci_delta'][0]:.2f}, {boot['ci_delta'][1]:.2f}] excludes_zero={boot['excludes_zero']}")
    print(f"  z 95% CI:     [{boot['ci_z'][0]:.2f}, {boot['ci_z'][1]:.2f}]")

    summary = pd.DataFrame([
        dict(control="within_class", subset="mixed", n=176, observed=obs_mixed_pca, z_gauss=z_gauss_mixed["z"]),
        dict(control="within_class", subset="tumor", n=int(tumor_mask.sum()), observed=obs_tumor, z_gauss=z_gauss_tumor["z"]),
        dict(control="within_class", subset="normal", n=int((~tumor_mask).sum()), observed=obs_normal, z_gauss=z_gauss_normal["z"]),
        dict(control="residualization", subset="intact", n=X_hvg_std.shape[0], observed=resid["intact"]["observed"], z_gauss=resid["intact"]["gauss"]["z"]),
        dict(control="residualization", subset="residualized", n=X_hvg_std.shape[0], observed=resid["residualized"]["observed"], z_gauss=resid["residualized"]["gauss"]["z"]),
    ])
    summary.to_csv(os.path.join(args.results_dir, "gse146889_audit_summary.csv"), index=False)
    strata_df.to_csv(os.path.join(args.results_dir, "gse146889_within_stratum.csv"), index=False)
    print(f"\nSaved results to {args.results_dir}")
    print(f"Total elapsed: {time.time()-t0:.0f}s")


if __name__ == "__main__":
    main()
